// customers.dart
// Example data file defining customer categories for the Animal Restaurant Progress Tracker.
// Each list contains names pulled from the Animal Restaurant wiki.
// You can extend or modify these lists as needed.

const List<String> regularCustomers = [
  'White Bunny',
  'Brown Bunny',
  'Deer',
  'Mouse',
  'Striped Yellow Jackal',
  'Badger',
  'Spotted Deer',
  'Artist Badger',
  'Wounded Bear',
  'Hedgehog',
  'Brown Wolf',
  'Striped Jackal',
  'Blueberry Hedgehog',
  'Sheep',
  'Yellow Jackal',
  'Swan',
  'Wolf',
  'Scarred Bear',
  'Granny Wolf',
  'Border Collie',
  'French Bulldog',
  'Bald Sheep',
  'Lop‑Eared Rabbit',
  'Otter',
  'One‑Eyed Papillon',
  'Fox',
  'Raccoon',
  'Terrier',
  'Field Dog',
  'Shiba',
  'Ostrich',
  'White Shiba',
  'Paper Bagged Ostrich',
  'Berry Hedgehog',
  'Chocolate Lab',
  'Chocolate Border Collie',
  'Boar',
  'Black Shiba',
  'Black Lab',
  'Boston Terrier',
  'Merle Border Collie',
  'Pug',
  'Corgi',
  'Speckled Pig',
  'Husky',
  'Tri‑Colored Corgi',
  'Pig',
  'Old Collie',
  'Fennec Fox',
  'Penguin',
  'White‑Collar Fox',
  'Lynx',
  'Dachshund',
  'Rescue Dog',
  'Sloth',
  'Polar Bear',
  'Slim White Dog',
  'Insta‑Pup',
  'Flamingo',
  'Gnome',
  'Mushroom Sloth',
  'Influencer Flamingo',
  'Tiger',
  'Little Black Dog',
  'White Rabbit',
  'Cheshire Cat',
  'Reporter',
  'Glamourous Lady',
  'Scotch Collie',
  "Programmer’s Dog",
  'Dalmatian',
  'Party Puppy',
  'Green‑Hat Gnome',
  'Cici',
  'Lucky Pig',
  'Shiba Puppy',
  'Alpaca',
  'Little Lion',
  'Abi',
  'Little Fox',
  'Squirrel',
  'Wild Duck',
  'Wood-chuckin\' Beaver',
  'Brown Horse',
  'Yorkie Mom',
  'Yorkie Dad',
  'Pink Piggy',
  'Yorkie Pup',
  'Bean',
  'Dr. Puppy',
  'Moon Rabbit',
  'Capybara',
  'Pangolin Baby',
  'Pangolin Mama',
  'Guru',
  'Red Squirrel',
  'Beaver Engineer',
  'Alaska',
  'Asian Elephant',
  'Hippopotamus',
  'Snow Leopard Pup',
  'Snow Leopard',
  'Adventurer Stoat',
  'Beancurd',
  'Rice Cake',
  'Moose',
  'Aries',
  'Curly',
  'Dorkie',
  'Little Koala',
  'Yannis',
  'Mooey',
  'Mr. Bharal',
  'Chihuahua',
  'Brown Chihuahua',
  'Black & White Chihuahua',
  'Lilith',
  'Rose',
  'Snowy',
  'Sleepwalking Little Lion',
  'Arctic Hare',
  'Mystifying Crane',
  'Nozy',
  'Black Papillon',
  'Eugene the Tree-kangaroo',
  'Bernese Mountain Pup',
  'Miss Rhino',
  'Manager Bear',
  'Golden Retriever',
  'Little Colt',
  'White Mouse',
  'Fancy Rat',
  'Grandpa Spirit Bear',
  'Amber',
  'Dracula',
  'Ahau',
  'Lil\' Duckling',
  'Longevity Fox',
  'Deer of Nine Colors',
  'Dragony',
  'Weeping Croc',
  'Axolotl',
  'Goofy',
  'Honey Badger',
  'Lil\' Giraffe',
  'Quokka',
  'German Shepherd',
  'Annie',
  'Harpy Eagle Wizard',
  'Black Panther',
  'Cong Cong',
  'Er Shu',
  'Cyborg Danny',
  'Fuzzy',
  'Meery',
  'Squiddy',
  'Lemur',
  'Elephant Shrew',
];

const List<String> specialCustomers = [
  'Rich Kid',
  'Ad Salesman',
  'Cod‑Stealing Rabbit',
  'Skunk',
  'Card‑Playing Mouse',
  'Wandering Singer',
  'New Year Mouse',
  'Rascal',
  "Rascal’s Dad",
  "Rascal’s Mom",
  'Christmas Elf',
  'New Year Calf',
  'Cowherd',
  'Weaver Girl',
  'Dani',
  'Halloween Ragdoll',
  'Snowball 2',
  'Auspicious Bunny',
  'Sugar Glider Mimi',
  'Blessed Dragon',
  'Felicity Nüwa',
  'Halloween Pumpkin',
  'Fortuneteller',
  'Mysterious Merchant',
  'Otter Dodo',
  'Mister Roach',
  'Chacha',
  'Tiger of Blessings',
];

const List<String> boothOwners = [
  'Traditional Popcorn',
  'Old Joe',
  'Portrait Drawing Booth',
  'Sketch Artist',
  'Picnicking Rabbit',
  'Hillside’s Stinkiest',
  'Picnicking Duck',
  'Prosperity Pineapple',
  'Wholegrain Pancake',
  'Convenience Buns',
  'Love‑filled Buns',
  'Reverie Cotton Candy',
  'Slum Cotton Candy',
  'Stray Wild Panda',
  'Scavenging Skinny Dog',
  'Candied Hawthorn',
  'Mouse Market',
  'Flower Shop',
  'Bunny’s Back Garden',
  'Garden Plot',
  'Cut Cake',
  'Flora’s Ring Toss',
  'Bamboo Hot and Sour Noodles',
  'Terrible Pancake',
  'Japanese Cuisine',
  'Raccoon’s Takoyaki',
  'Rabbit’s Breakfast',
  'Hedgehog’s Breakfast',
  'Sweet Malt Candy',
  'Scavenging Puppies and Kitties',
  'Beancurd Dessert',
  'Bowl Pudding',
  'Ice Cream Stall',
  'Golden Fried Potatoes',
  'American Hot Dog',
  'Honeydew Shaved Ice',
  'Traditional Bowl Pudding',
  'Fresh Glutinous Rice Cake',
  'Egg Waffle',
  'Tailor Liu',
  'Love Salon',
  'Fried Quail Eggs',
  'Ice Cream Truck',
  'Street Stall Hiring',
  'Summer Iced Jelly',
  'Piggy’s Crawdads',
  'Skillful Massage',
  'Rainbow Shop Stationery',
  'Bicycle Repairs',
  'Encounters Photo Studio',
  'Love Tribe',
  'Fortunetelling',
  'Professional Protectors',
  'Gold Tooth Antiques',
  'Another Roujiamo',
  'Swift Roti Prata',
  'Trendy Braid',
  "Uncle’s Roasted Sweet Potato",
  'Inconspicuous Roasted Chestnuts',
  'Romantic Hot Air Balloon',
  "Budget Witchs Soup",
  'Sticky Rice Balls',
  'Ink Calligraphy',
];

const List<String> seasonalCustomers = [
  'Praying Samoyed',
  'Tom',
  'Duke Swallow',
  'Mister Gecko',
];

const List<String> performers = [
  'Cutie White Bunny',
  'Cutie Hamster',
  'Cutie Goose',
  'Cutie Guru',
  'Little Piggy Angel',
  'Little Turtle Angel',
  'Little Yorkie Angel',
  'Little Shiba Angel',
  'Bassist Toad',
  'Guitarist Toad',
  'Vocalist Toad',
  'Drummer Toad',
  'Vocalist Samoyed',
  'Guitarist Husky',
  'Bassist Border Collie',
  'Accompanist Penguin',
  'Lead Dancer Slim White Dog',
  'Lead Singer Dalmatian',
  'Rapper Bean',
  'Leader Scotch Collie',
  'Leader Pug',
  'Guitarist Jackal',
  'Bassist Brown Wolf',
  'DJ Wolf',
];

const List<String> staff = [
  'Messenger Hedwig',
  'Fisherman Rabbit Ding',
  'Jiji the Waiter',
  'Chef Gumi',
  'Timmy the Server',
  'Prince the Gardener',
  'Temp Worker Yolky',
  'Eggy the Handyman',
];

/// Combined list of all customers.
final List<String> allCustomers = [
  ...regularCustomers,
  ...specialCustomers,
  ...seasonalCustomers,
  ...boothOwners,
  ...performers,
];
