// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxhIVnFUPl8BneWDMk1MLwGczxgePYQrQ',
    appId: '1:174067290396:web:268ea177d8e5c3ffc66ad9',
    messagingSenderId: '174067290396',
    projectId: 'ar-progress-tracker-1b3d8',
    authDomain: 'ar-progress-tracker-1b3d8.firebaseapp.com',
    storageBucket: 'ar-progress-tracker-1b3d8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu7NFv3qk1BvfcfPETyZCLt9nT_5YBoWg',
    appId: '1:174067290396:android:b1fa5d08ea39346ac66ad9',
    messagingSenderId: '174067290396',
    projectId: 'ar-progress-tracker-1b3d8',
    storageBucket: 'ar-progress-tracker-1b3d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_dc_bhphRuYGQqVIpKFppM0hXBdYDiFM',
    appId: '1:174067290396:ios:9d65a4a394981871c66ad9',
    messagingSenderId: '174067290396',
    projectId: 'ar-progress-tracker-1b3d8',
    storageBucket: 'ar-progress-tracker-1b3d8.firebasestorage.app',
    iosBundleId: 'com.example.animalRestaurantTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_dc_bhphRuYGQqVIpKFppM0hXBdYDiFM',
    appId: '1:174067290396:ios:9d65a4a394981871c66ad9',
    messagingSenderId: '174067290396',
    projectId: 'ar-progress-tracker-1b3d8',
    storageBucket: 'ar-progress-tracker-1b3d8.firebasestorage.app',
    iosBundleId: 'com.example.animalRestaurantTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxhIVnFUPl8BneWDMk1MLwGczxgePYQrQ',
    appId: '1:174067290396:web:9b211358bdf128b8c66ad9',
    messagingSenderId: '174067290396',
    projectId: 'ar-progress-tracker-1b3d8',
    authDomain: 'ar-progress-tracker-1b3d8.firebaseapp.com',
    storageBucket: 'ar-progress-tracker-1b3d8.firebasestorage.app',
  );
}
