//   /// Names for performers【625433312635769†L617-L663】.  These characters are
//   /// musicians or entertainers who play in bands or singing groups.] 
//   final List<String> performers = [
//     'Cutie White Bunny',
//     'Cutie Hamster',
//     'Cutie Goose',
//     'Cutie Guru',
//     'Little Piggy Angel',
//     'Little Turtle Angel',
//     'Little Yorkie Angel',
//     'Little Shiba Angel',
//     'Bassist Toad',
//     'Guitarist Toad',
//     'Vocalist Toad',
//     'Drummer Toad',
//     'Vocalist Samoyed',
//     'Guitarist Husky',
//     'Bassist Border Collie',
//     'Accompanist Penguin',
//     'Lead Dancer Slim White Dog',
//     'Lead Singer Dalmatian',
//     'Rapper Bean',
//     'Leader Scotch Collie',
//     'Leader Pug',
//     'Guitarist Jackal',
//     'Bassist Brown Wolf',
//     'DJ Wolf',
//     'Piano Contender'
//     'Bamboo Hand Fan',
//     'Natural Comedian',
//     'Chopper',
//     'Probiotic Panther',
//     'Frisky Pangolin',
//     'Zippy Koala',
//     'Sweetie Curly',
//     'DuBond',
//     'Louise',
//     'Danielle',
//     'Marcus',
//     'Pretty Face',
//     'Drunken Rouge',
//     'Exquisite Jade',
//     'Princess Feather',
//     'Rat-a-tat',
//     'Dingle-dangle',
//     'Ta-da-da',
//     'Thump-thump',
//     'Busy Bee-trice',
//     'Steady Sally',
//     'Gentle Grace',
//     'Elegant Emily',
//     'Backing Vocalist Beaver',
//     'Soloist Beaver',
//     'Accompanist Beaver',
//     'Backup Dancer Beaver',
//     'Aaron',
//     'Belle',
//     'Ella',
//     'Chris',
//     'Windrider',
//     'Moondancer',
//     'Cloudmaster',
//     'Snowwalker',
//     'Minty Star',
//     'Frosty Star',
//     'Pudding Star',
//     'Honey Star'
// ];